name: 'github_stars'
version: '1.0.0'

profile: 'github_stars'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# directories to be removed by `dbt clean`
clean-targets:         
  - "target"
  - "dbt_packages"


# Configuring models
models:
  github_stars:
  
    staging:
      +materialized: view
  
    marts:
      +materialized: table

    
    
    
